# Generated by Django 3.1.7 on 2021-04-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=40, verbose_name='username')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('active', models.BooleanField(default=True, verbose_name='is active')),
                ('staff', models.BooleanField(default=False, verbose_name='is staff')),
                ('superuser', models.BooleanField(default=False, verbose_name='is super user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
