# Generated by Django 3.1.7 on 2021-04-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_auto_20210422_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='campagins/'),
        ),
    ]
